version: '3.9'

services:
  server:
    container_name: planmkt-server
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
          WWWGROUP: '${WWWGROUP}'
          NODE_VERSION: '18'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - planmkt-network

  db:
    image: mysql:8.0
    container_name: planmkt-database
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - planmkt-network

  db_test:
    image: mysql:8.0
    container_name: planmkt-database-test
    environment:
      MYSQL_DATABASE: "${DB_TEST_DATABASE}"
      MYSQL_USER: "${DB_TEST_USERNAME}"
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: "${DB_TEST_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_TEST_PASSWORD}"
    volumes:
      - db_test:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - planmkt-network

  redis:
    container_name: planmkt-redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - planmkt-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  planmkt-network:
    name: plantmkt
    driver: bridge

volumes:
  db:
    name: planmkt-database
    driver: local
  db_test:
    name: planmkt-database-test
    driver: local
  redis:
    name: planmkt-redis
    driver: local