name: CI

on:
  push:
    branches:
      - "feature/*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install dependencies
      run: npm install && composer install

    - name: Start Containers with Database Test Only
      run: docker-compose -f "docker-compose.yaml" up -d --build server db_test
  
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Run tests
      run: php artisan test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down